using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using Dapper;

namespace Jaunty
{

    /// <summary>
    /// Defines a set of attributes for filtering
    /// </summary>
    [Flags]
    public enum PropertyFlags
    {
        /// <summary>
        /// This property is part of a key
        /// </summary>
        Key = 1,
        /// <summary>
        /// This property is generated by the database
        /// </summary>
        DatabaseGenerated = 2,
        /// <summary>
        /// This property should be ignored by any SQL operations
        /// </summary>
        SqlIgnore = 4
    }

}
